Repository theforeman/foreman_discovery, pull requests merged in 2018-06, with the labels that each got.

#431 Fixes #23488 - Port robottelo tests for discovery_rule
  test/functional/api/v2/discovery_rules_controller_test.rb
  test/unit/discovery_rule_test.rb
Labels: Needs testing

#425 Fixes #23278 - Migrate two-pane to breadcrumb-bar
  app/views/discovery_rules/_form.html.erb
  app/views/discovery_rules/edit.html.erb
  app/views/discovery_rules/index.html.erb
Labels: Needs re-review, Needs testing

#410 Fixes #22581 - root password is not overriden
  app/models/host/discovered.rb
Labels: Needs testing, Not yet reviewed

#440 Fixes #23860: use success instead of notice
  app/controllers/discovered_hosts_controller.rb
Labels: Needs testing

#438 Fixes #23793 - Port robottelo tests for settings
  .rubocop_todo.yml
  test/functional/api/v2/settings_controller_test.rb
  test/models/setting_test.rb
Labels: Needs testing, Not yet reviewed

#391 Fixes #21653 - render delegated nil correctly
  app/models/host/discovered.rb
Labels: Needs testing, Not yet reviewed

#430 Fixes #3862 - audit host discovery
  app/models/host/discovered.rb
Labels: Needs testing, Not yet reviewed

#403 Fixes #22193 - priorize NIC with IP
  app/services/foreman_discovery/fact_parser.rb
  extra/discovery/pxeless-vlan.json
Labels: Needs testing, Not yet reviewed

#437 Fixes #16330 - random and MAC name generators
  app/models/host/discovered.rb
  app/models/setting/discovered.rb
  test/test_helper_discovery.rb
  test/unit/host_discovered_test.rb
Labels: Needs testing

#436 Fixes #23224 - keep_subnet flag to prevent subnet override
  app/services/foreman_discovery/fact_parser.rb
  lib/foreman_discovery/engine.rb
  test/unit/host_discovered_test.rb
Labels: Needs testing

#432 Fixes #23554 - Handle both cases of options[:user] as arrive from foreman
  app/mailers/discovered_mailer.rb
  test/unit/discovered_mailer_test.rb
Labels: Needs testing
