Repository theforeman/foreman_discovery, pull requests merged in 2018-03, with the labels that each got.

#398 Fixes #21935 - Notifications for org admins too
  app/models/host/discovered.rb
  app/services/foreman_discovery/ui_notifications/new_host.rb
  test/unit/host_discovered_test.rb
  test/unit/ui_notifications/destroy_host_test.rb
  test/unit/ui_notifications/new_host_test.rb
Labels: Needs testing

#413 Fixes #22933 - fix functional test case for reboot all hosts
  test/functional/discovered_hosts_controller_test.rb
  test/integration/discovered_hosts_test.rb
  test/unit/host_discovered_test.rb
Labels: Needs testing, Not yet reviewed

#411 Fixes #22783 - Audit discovery resources
  app/models/discovery_rule.rb
  test/unit/discovery_rule_test.rb
Labels: Needs testing, Ready to merge

#414 Fixed #22941 - better error with filters
  app/services/foreman_discovery/fact_parser.rb
  extra/discover-host
  test/unit/fact_parser_test.rb
  test/unit/host_discovered_test.rb
  test/unit/ui_notifications/new_host_test.rb
Labels: Needs testing, Not yet reviewed

#412 Fixes #22932 - unprocessible contains backtrace
  app/controllers/api/v2/discovered_hosts_controller.rb
Labels: Needs testing
