Repository theforeman/foreman_discovery, pull requests merged in 2021-11, with the labels that each got.

#557 Fixes #33917 - skip invalid IP address
  app/services/foreman_discovery/subnet_suggestion.rb
Labels: Needs testing, Not yet reviewed

#558 Fixes #33926 - add necessary puppet helpers
  app/controllers/discovered_hosts_controller.rb
Labels: Needs testing

#555 Add Puppet params with puppet plugin
  app/controllers/concerns/foreman/controller/parameters/discovered_host.rb
Labels: Needs testing, Not yet reviewed

#559 Fixes #33998 - EnsureNotUsedBy has no namespce
  app/models/concerns/discovery_taxonomy_extensions.rb
Labels: Needs testing

#556 Fixes #33770 - create notification only for new hosts
  app/models/host/discovered.rb
Labels: Needs testing, Waiting on contributor
