Repository theforeman/foreman_discovery, pull requests merged in 2022-07, with the labels that each got.

#573 Fixes #35188 - fix puppet plugin detection for permissions issues
  lib/foreman_discovery/engine.rb
Labels: Needs testing, Cherry-pick needed

#576 Version 19.0.5
  lib/foreman_discovery/version.rb
Labels: Needs testing, Not yet reviewed

#575 Allow to translate Foreman Discovery
  webpack/src/ForemanDiscovery/DiscoveredHosts/Components/EmptyState/EmptyState.js
Labels: Needs testing
